#  see: https://www.appveyor.com/docs/build-environment/#build-vm-configurations
#  for details on the AppVeyor build VM configurations
environment:
    matrix:
          - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
            PYTHON_VERSION: "3.5"
            MINICONDA_DIR: "C:\\Miniconda35-x64"
          - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
            PYTHON_VERSION: "3.6"
            MINICONDA_DIR: "C:\\Miniconda36-x64"
          - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
            PYTHON_VERSION: "3.7"
            MINICONDA_DIR: "C:\\Miniconda36-x64"
          - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
            PYTHON_VERSION: "3.7"
            MINICONDA_DIR: "C:\\Miniconda37-x64"


# SCS is a required solver, and it has no 32 bit distribution
# on conda; cvxpy's AppVeyor tests will only use 64 bit Windows.
platform:
    - x64

# The install phase is contained in two PowerShell scripts.
install:
    - ps: echo $env:MINICONDA_DIR
    - ps: echo $env:path
    - ps: $env:path="$env:MINICONDA_DIR;$env:MINICONDA_DIR\Scripts;$env:MINICONDA_DIR\Library\bin;$($env:path)"
    - cmd: '"%MINICONDA_DIR%\Scripts\activate.bat"'
    - cmd: conda config --set always_yes yes --set changeps1 no
    - cmd: conda update --quiet conda
    - cmd: conda install -n root conda conda-env anaconda-client
    - "powershell continuous_integration\\AppVeyor\\configure_conda_and_install_cvxpy.ps1"

# Not a .NET project, we build CVXPY in the install step instead.
build: false

# The test phase uses Windows CMD commands (not PowerShell).
test_script:
    - "conda activate testenv"
    - "conda env list"
    - "nosetests cvxpy"

deploy_script:
    - "powershell continuous_integration\\AppVeyor\\deploy_windows.ps1"
